// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtZ7OGInn8Z3Kd9EHe7T6NoXaEjF57wRw',
    appId: '1:769573772876:web:19bf5360a5ef1985975ee9',
    messagingSenderId: '769573772876',
    projectId: 'project-management-app-a5418',
    authDomain: 'project-management-app-a5418.firebaseapp.com',
    storageBucket: 'project-management-app-a5418.appspot.com',
    measurementId: 'G-TEZK9RY670',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu9iTeOIe7aAkPA0CNwmMnsQe6ago5YeA',
    appId: '1:769573772876:android:ab9f32e6d279654d975ee9',
    messagingSenderId: '769573772876',
    projectId: 'project-management-app-a5418',
    storageBucket: 'project-management-app-a5418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCujakq0qQ1Fk0lr6uymnfgLd6LMWPBInQ',
    appId: '1:769573772876:ios:dcb1a8109a90cac3975ee9',
    messagingSenderId: '769573772876',
    projectId: 'project-management-app-a5418',
    storageBucket: 'project-management-app-a5418.appspot.com',
    iosBundleId: 'com.example.projectManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCujakq0qQ1Fk0lr6uymnfgLd6LMWPBInQ',
    appId: '1:769573772876:ios:f99c5006e370f354975ee9',
    messagingSenderId: '769573772876',
    projectId: 'project-management-app-a5418',
    storageBucket: 'project-management-app-a5418.appspot.com',
    iosBundleId: 'com.example.projectManagement.RunnerTests',
  );
}
